### ISSUE TITLE
Implement SeqEntry class from UML diagram

### ISSUE THREAD

**Issue by ahovgaard** [BIO-DIKU/klust#14]
I started this in the `seq_entry` branch.

**Comment by maasha** [comment]
I have operated for years with a simple SeqEntry class which the following
members:
- String sequence - the DNA or Protein sequence.
- String sequence name - the name of the sequnce.
- String type - sequence type - DNA, RNA or Protein.
- String scores - the ascii encoded quality scores.

**Comment by ahovgaard** [comment]
Just to make sure: Are we still going with the above SeqEntry class?

**Comment by maasha** [comment]
We probably want to have the scores as a vector of shorts instead of a String. And call the members seq, name, type and scores.

**Comment by ahovgaard** [comment]
Okay, I'll update the names.
Why a vector of shorts, shouldn't 8 bits per score be enough? Otherwise, I think we should use `int16_t` instead of `short`.

**Comment by maasha** [comment]
While 8 bit is compact, converting downstream is going to be a pain. And do use standard integer types like int16_t.
