### ISSUE TITLE
Proper Fasta class

### ISSUE THREAD

**Issue by AndreasDahl** [BIO-DIKU/klust#38]
Proper class for reading and writing fasta files
- Reading IO
- Writing SeqEntry IO
- Iterator

**Comment by AndreasDahl** [comment]
See https://github.com/BIO-DIKU/BioIO

**Comment by AndreasDahl** [comment]
What is the scope of this issue? When can we close it?

**Comment by maasha** [comment]
Problem moved to BioIO, so we close it here.
