### ISSUE TITLE
Header guards: KLUST_<file>_H_ vs. SRC_<file>_H_ ?

### ISSUE THREAD

**Issue by ahovgaard** [BIO-DIKU/klust#45]
Do we follow the C++ style guide and use e.g.

``` cpp
#ifndef KLUST_SEQUENCE_H_
```

or the format dictated by the `cpplint` tool?

``` cpp
#ifndef SRC_SEQUENCE_H_
```

**Comment by maasha** [comment]
Me things the basedir is `src` and that should not be included - that is we follow the style guide. I think cpplint may either be buggy or uses somehow the include path, which may be wrong. @RasmusFonseca ?

**Comment by RasmusFonseca** [comment]
Yes, sounds like something wrong with cpplint. Havent played that much with it yet. But SRC_ should definitely not be in the header guards

**Comment by ahovgaard** [comment]
It seems like the `cpplint` tool expects a directory structure like `src/klust/<code>`. It is possible to specify a root directory to `cpplint`, but I can only get it working with `cpplint --root=src`, which makes it expect guards like `SEQ_ENTRY_H_`.

**Comment by AndreasDahl** [comment]
I wouldn't mind the `src/klust/<code>` directory structure.

**Comment by maasha** [comment]
So if you read the guidelines:

https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#The__define_Guard

the header guard for the file

`klust/src/modules/kmer_gen.h`

should be

`KLUST_MODULES_KMERGEN_H_`
