### ISSUE TITLE
Less testing of KmerCollection

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/klust#48]
There are many redundant tests (lines 60-77). The relevant tests are:
- test that ++ increments correctly.
- test that ++ behaves correctly at iteration termination.
- test that -- decrements correctly.
- test that -- behaves correctly at iteration start.

Moveover, use a minimal testing example - maybe a sequence of length 3 and a kmer size 2.

**Comment by ahovgaard** [comment]
What is the correct behavior for `++` past the end or `--` past the beginning?
Or should we just test that `it == end()` at the expected time?

**Comment by maasha** [comment]
Same behaviour as if you overstep a string iterator I should say. What does that do?

**Comment by ahovgaard** [comment]
I think the behavior is undefined. I tried a simple test of iterating past the end of a string and I just got a lot of `NUL` bytes and eventually a segfault.

**Comment by maasha** [comment]
In that case we eliminate the "behaves correctly" tests, and state clearly in the documentation that the behavior is undefined.
