### ISSUE TITLE
Use BioIO in klust

### ISSUE THREAD

**Issue by ahovgaard** [BIO-DIKU/klust#57]
For instance by cloning BioIO repository when making.

**Comment by AndreasDahl** [comment]
We can have it as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if you dare.

**Comment by maasha** [comment]
Unfortunately there is a Github "feature" which prevents submodules from being included in tagged releases. So the way to go is either clone while making, as @ahovgaard  suggested, or include the library in the klust releases.
