### ISSUE TITLE
Linking with BioIO SeqEntry not working

### ISSUE THREAD

**Issue by ahovgaard** [BIO-DIKU/klust#63]
I can't seem to get `klust` working with BioIO's SeqEntry. I include it with:

``` cpp
#include <BioIO/seq_entry.h>
```

and it almost compiles, but fails with link errors like the following:

```
CMakeFiles/klust.dir/src/fasta_writer.cc.o: In function `FastaWriter::write(SeqEntry const&)':
/home/akh/uni/BIO-DIKU/klust/src/fasta_writer.cc:72: undefined reference to `SeqEntry::seq() const'
```

**Comment by maasha** [comment]
Hm, are the BioIO tests are passing and do they include testing of `FastaWriter::write`?

**Comment by ahovgaard** [comment]
I am trying to make `klust` use the `SeqEntry` class from BioIO instead of the older version currently in `klust`. BioIO does not have a `FastaWriter` class yet. I think it's just a problem with linking or something and not about BioIO.

**Comment by ahovgaard** [comment]
I got it working now.  I moved this part of `CMakeLists.txt`:

``` cmake
# Link BioIO
include_directories(${bioio_INSTALL_DIR}/include)
link_libraries(${bioio_INSTALL_DIR}/lib/libBioIO.a)
```

above the `add_executable` part. I also removed the `${BIOIO_LIBRARY}` variable references since I cannot see it defined anywhere and it works without.

**Comment by maasha** [comment]
Super, close the issue then.
